### ISSUE TITLE
PAM module path on openSUSE

### ISSUE THREAD

**Issue by dianagudu** [EOSC-synergy/pam-ssh-oidc-packaging#2]
It looks like the default module path on suse systems (only tested on 15.2 so far) is `/lib64/security/`, but the pam-ssh module is installed in `/usr/lib64/security/`.

An easy fix would be to use the absolute path in `/etc/pam.d/sshd_config`:

```
auth   sufficient /usr/lib64/security/pam_oidc_token.so config=/etc/pam.d/pam-ssh-oidc-config.ini
```

**Comment by marcvs** [comment]
Fixed
